#!/bin/sh
set -e

cat << EOF > $target/etc/default/u-boot
U_BOOT_FDT=$fdtfile
U_BOOT_PARAMETERS="rw rootwait"
EOF

for kernel in $target/boot/vmlinuz-*
do
    ver=$(echo $kernel|sed -e 's,.*vmlinuz-,,')
    chroot $target /usr/sbin/update-initramfs -c -k $ver||true
done

chroot $target /usr/sbin/u-boot-update||true
